pipeline {
    agent any
    tools {
        maven "MAVEN3.9.14"
        jdk "JDK17" 
    }
    stages {
        stage('Fetching code from GitHub') {
            steps{
                git branch: 'atom', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }
        }
        
        stage('Run unit tests') {
            steps{
                sh 'mvn test'
            }
        }
        
        stage('Build the project') {
            steps {
                sh 'mvn install -DskipTests'
            }
            post {
                success {
                    echo 'Build successful!'
                    archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
                }
                failure {
                    echo 'Build failed. Please check the logs.'
                }
            }
        }
    }
}
